### ISSUE TITLE
Many ungraded assignments not showing and some graded ones showing

### ISSUE THREAD

**Issue by KeironWalsh** [remotelearner/moodle-block_grade_me#12]
We have found the grade me menu to be a fantastic and invaluable module; however, having had the row num issue and upgrading to resolve it, we are now finding that some student's submitted assignments are not appearing, yet others that have already been graded are appearing in the menu as ungraded.

The "Grading Summary" on each assignment page correctly shows the number of participants, the number submitted and the number in need of grading.

Our tutors have come to depend on this module, as it is so useful and we really would like to continue using it.

Kind Regards

Keiron

**Comment by goose2001** [comment]
Hi, I'm seeing this as well? Is it possible to rebuild the database? Thanks
Dan

**Comment by drachels** [comment]
Probably part of the same problem - I've just noticed that using the new 3.1.0.1 version of Grade Me, that if I click on a checkmark in the Grade Me block to go grade a student, then exit the grading page without actually giving a grade, that student is no longer listed in the Grade Me block as needing to be graded. Is this a bug, or is it expected behavior?

**Comment by KeironWalsh** [comment]
Before we had the problem I described above, we did have the issue that you describe, drachels. Although it only did it if the tutor clicked on _Save_ without actually grading it.

There has been an upgrade to the block this morning, so I will see if it resolves the issue and post back here if it does.

Keiron
