### ISSUE TITLE
Feature request - Clicking the student's name would lead to his submission and not to his profile

### ISSUE THREAD

**Issue by acquaalta** [remotelearner/moodle-block_grade_me#59]
Hi,
Currently (Version 3.11.0.2 of the plugin), When the teacher clicks on the student name, the profile page of the student is shown.
Only when clicking the "V" sign besides the name, the student's submission is shown.
UX-wise, I think it's better to show the submission when clicking the student's name, or at least create a plugin setting for it and let the administrator decide about the expected behavior of the plugin.

Please consider it :-)

**Comment by gemguardian** [comment]
@acquaalta It is about removing row 222 and 225 in the lib.php 

I put in a pull request for 3.9 (https://github.com/remotelearner/moodle-block_grade_me/pull/60) 
3.11 https://github.com/remotelearner/moodle-block_grade_me/pull/61
and 4.0 https://github.com/remotelearner/moodle-block_grade_me/pull/62

**Comment by drachels** [comment]
Question...in the rest of Moodle anytime I click on a user name, I go to their profile. Why would you want to change that behavior for this plugin and make it different from all the rest? Also, it is a checkmark, not a "v".

**Comment by gemguardian** [comment]
@drachels 

We got the request to remove the profile link for the following reason:

The users that where grading got confused, they though when they clicked on thename they go to the grading page instead of the profile. This is why I have removed the url to the profile page, I have considered to just change the link to the grading page. 

As well to be honest - why would you navigate to a profile page as a teacher when you main purpose is using the block for grading? As you state there are other ways to navigate to a profile page, and I believe from a good UI purpose you should only make this possible in the places where it makes most sense. And it does not make sense for my users and/or @acquaalta  users in this case to do this from the Grade me Block. 
But that's  just my 2 cents on this. 

The provided pull request can be either integrated or just used by those who need it. 
The most neat why would be as @acquaalta suggested to make it a setting, but that is above my personal coding skills :) But feel free to adjust the patch in to do this. 

Gemma

**Comment by drachels** [comment]
Sounds reasonable, and I freely admit, I have clicked the name on more than one occasion. I know that in many plugins it is pretty obvious that the name is going to go to the profile, but the way the GradeMe block looks it is always tempting to click the name.

**Comment by gemguardian** [comment]
I am waiting the response if it makes sense to hyperlink the name as well to the graded assignement, it's just a small adjustment in the provided patch. But at the moment they said that the "V" mark is clear enough to click.

**Comment by acquaalta** [comment]
Hi @gemguardian,
Thanks for your help. I have a question:
I looked at your pull request. It seems that you removed the link (<a> tag) from the name of the student(s). How does make the name a link to the grading page of that student? I'm missing something.

**Comment by gemguardian** [comment]
@acquaalta sorry for the confusing, my teachers though it was clear enough if the name was not clickable just the V mark. 

They just bumped into the confusion that it went to the profile page. But the adjustment for clickable name to grading is not that difficult, though I don't see any movement in the pull request that are being done, so I don't bother right now on changing anything.

**Comment by ghost** [comment]
Hello, as the block currently works this is intended functionality.  Clicking the user's name will take you to their profile page, while clicking the check-mark icon next to their name will take you to the assignment submission for grading.
