### ISSUE TITLE
Grade me block showing to all users including students (Moodle 4.05)

### ISSUE THREAD

**Issue by cdipe** [remotelearner/moodle-block_grade_me#64]
The block is showing to all users, that is confusing for other users than graders (Moodle 4.05)

**Comment by ghost** [comment]
I'm unable to reproduce this on either the latest published version of block_grade_me v4.0.0.0 running on Moodle 4.0.5+ (Build: 20230105), or with the in-progress version I'm working on for Moodle 4.1.  On a fresh installation of Moodle when I add the Grade Me block to either the site homepage configured to display site-wide, or to an individual course homepage, I get the same result: the Grade Me block is _not_ visible to student users but is visible to users with the non-editing teacher (or greater) role within the course and to site admins.

It sounds like you may have either granted additional permissions on selected capabilities to the Student role, or the given students may have an additional role assigned which inherits permissions from the non-editing teacher (or greater) role.  You'll need to recheck the permissions granted to your student user's assigned roles, since this doesn't seem to happen with the default role permissions.

**Comment by cdipe** [comment]
@logan-reynolds thank you, it's working with later versions.
